### ISSUE TITLE
(\d{4,5}|\d{1,4}万)再生

### ISSUE THREAD

**Issue by eggplants** [SnO2WMaN/niconico-n-plays-tag#1]
`\d{1,3}再生`に加えて、`(\d{4,5}|\d{1,4}万)再生`も是非調べて欲しいです♪

**Comment by SnO2WMaN** [comment]
:ok:

**Comment by SnO2WMaN** [comment]
もともと本旨は泡沫の**n再生**タグを調べるためなので，一旦閉じます

4ケタ再生数でおもしろいタグがあればまた検証します
